major_parts:
  0: rightreardoor
  1: leftroofside
  2: leftrunningboard
  3: leftfoglamp
  4: frontws
  5: rightbpillar
  6: rightrunningboard
  7: leftfender
  8: lefttaillamp
  9: leftfrontdoor
  10: rightroofside
  11: rightheadlamp
  12: righttaillamp
  13: frontbumpergrille
  14: leftheadlamp
  15: frontbumper
  16: rearbumpercladding
  17: rightfrontdoor
  18: rightfoglamp
  19: bonnet
  20: tyre
  21: rearbumper
  22: leftapillar
  23: rearws
  24: leftreardoor
  25: leftbpillar
  26: tailgate

MAJOR_PARTS_NO_DIRECTION:
  0: frontbumpergrille
  1: roofside
  2: headlamp
  3: apillar
  4: foglamp
  5: runningboard
  6: bonnet
  7: rearws
  8: bpillar
  9: frontbumper
  10: frontws
  11: tailgate
  12: rearbumpercladding
  13: frontdoor
  14: tyre
  15: reardoor
  16: fender
  17: taillamp
  18: rearbumper

CATEGORY_MAPP:
  0: None
  1: front
  2: rear
  3: leftFront
  4: leftRear
  5: rightFront
  6: rightRear

CATEGORY_RULES:
  front:
    top:
      frontws
      roof
    bottom:
      frontbumper
    left:
      leftfoglamp
      leftheadlamp
    right:
      rightfoglamp
      rightheadlamp
    mustALL:
      frontbumpergrille
      bonnet
  rear:
    top:
      rearws
      roof
    bottom:
      rearbumper
      rearbumpercladding
    left:
      lefttaillamp
    right:
      righttaillamp
    #mustALL:
    #  rearbumpercladding all cars didn't labeled

  leftFront:
    top:
      leftroofside
      leftapillar
      leftfender
      roof
    bottom:
      tyre
    front:
      frontbumper
      leftheadlamp
    rear:
      leftbpillar
    mustALL:
      leftfrontdoor
      leftrunningboard


  leftRear:
    top:
      leftroofside
      roof
    bottom:
      tyre
    front:
      leftbpillar
    rear:
      rearbumper
      lefttaillamp
    center:
      leftreardoor
      leftrunningboard

  rightFront:
    top:
      rightroofside
      roof
    bottom:
      tyre
    rear:
      rightbpillar
    front:
      rightheadlamp
      frontbumper
    mustALL:
      rightfrontdoor
      rightrunningboard

  rightRear:
    top:
      rightroofside
      roof
    bottom:
      tyre
    front:
      rightbpillar
    rear:
      rearbumper
      righttaillamp
    mustALL:
      rightreardoor
      rightrunningboard

# NO in use
#CarFaceDirection:
#  right_rear:
#    rightbpillar:
#      bottom:
#        tyre
#      left:
#        rearbumper
#      top:
#        rightroofside
#        roof
#  rightFront:
#    rightbpillar:
#      top:
#        rightroofside
#        roof
#      bottom:
#        tyre
#      right:
#        rightheadlamp
#        frontbumper
#
#  leftFront:
#      leftbpillar:
#        top:
#          leftroofside
#          leftapillar
#          leftfender
#          roof
#        bottom:
#          tyre
#        left:
#          frontbumper
#          leftheadlamp
#  leftRear:
#    leftbpillar:
#      top:
#        leftroofside
#        roof
#      bottom:
#        tyre
#      right:
#        rearbumper
#        lefttaillamp
#      center:
#        leftreardoor
#        leftrunningboard
#  front:
#    bonnet:
#      top:
#        frontws
#        roof
#      bottom:
#        frontbumper
#      left:
#        leftfoglamp
#        leftheadlamp
#      right:
#        rightfoglamp
#        rightheadlamp
#      mustALL:
#        frontbumpergrille
#  rear:
#    rearws:
#      top:
#        roof
#      bottom:
#        rearbumper
#        rearbumpercladding
#      left:
#        lefttaillamp
#      right:
#        righttaillamp
#    #mustALL:
#    #  rearbumpercladding all cars didn't labeled



#success: 597, fails:692, total:1289
#defaultdict(<class 'int'>, {'foglamp': 37, 'tailgate': 355, 'runningboard': 171, 'roofside': 100, 'headlamp': 22, 'apillar': 33, 'fender': 20, 'taillamp': 17, 'frontdoor': 76, 'reardoor': 48, 'bpillar': 74, 'rearbumpercladding': 31, 'rearws': 8, 'bonnet': 9, 'tyre': 2, 'rearbumper': 16, 'frontbumpergrille': 4, 'frontbumper': 3, 'frontws': 5})


#success: 1067, fails:222, total:1289
#defaultdict(<class 'int'>, {'headlamp': 24, 'fender': 50, 'taillamp': 7, 'apillar': 24, 'frontdoor': 15, 'runningboard': 24, 'rearbumpercladding': 25, 'rearws': 2, 'frontbumper': 14, 'frontws': 10, 'roofside': 35, 'bpillar': 14, 'tyre': 1, 'bonnet': 11, 'foglamp': 15, 'frontbumpergrille': 3, 'reardoor': 4, 'rearbumper': 17, 'tailgate': 4})



